"use client";

import type { Email } from "@/types";
import {
  Archive,
  Star,
  CornerUpLeft,
  Calendar,
  Sparkles,
  ChevronDown,
  ChevronRight,
  User,
  Loader2,
  Send,
  PlusCircle,
  ExternalLink,
  MailX,
} from "lucide-react";
import { useState } from "react";
import PriorityBadge from "./PriorityBadge";
import ShieldBadge from "./ShieldBadge";
import { SensitiveEmailBody } from "./SensitiveEmailBody";
import { format } from "date-fns";
import { api } from "@/trpc/react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";

// Clean up ugly text artifacts generated by plaintext email fallbacks
function cleanEmailText(body: string) {
  if (!body) return "";
  return body
    .replace(/\[image:\s*[^\]]+\]/gi, "") // Remove [image: Google] tags
    .replace(/\[([^\]]+)\]\((https?:\/\/[^\s\)]+)\s*\)/g, "[$1]($2)") // Fix broken markdown links
    .replace(/(https?:\/\/[^\s\)]+)/g, (match, url) => {
      // Auto-link raw URLs if they aren't already in markdown brackets
      if (body.includes(`](${url})`) || body.includes(`](${url}`)) return match;
      return `[${url}](${url})`;
    });
}

interface EmailThreadProps {
  threadId: string;
  emailsInThread: Email[];
  isLoading: boolean;
  onArchive: (gmailId: string) => void;
  onToggleStar: (gmailId: string, starred: boolean) => void;
  onReply: (body: string) => Promise<void>;
  isReplying: boolean;
  onScheduleMeeting?: (extracted: {
    title: string;
    attendees: string[];
    suggestedTime: string;
    duration: number;
    description?: string;
  }) => void;
}

export default function EmailThread({
  threadId,
  emailsInThread,
  isLoading,
  onArchive,
  onToggleStar,
  onReply,
  isReplying,
  onScheduleMeeting,
}: EmailThreadProps) {
  // Expand/collapse message indexes (default only show last message expanded)
  const [expandedIds, setExpandedIds] = useState<Record<string, boolean>>({});
  const [replyBody, setReplyBody] = useState("");
  const [isDrafting, setIsDrafting] = useState(false);
  const [isExtracting, setIsExtracting] = useState(false);
  const [isUnsubscribing, setIsUnsubscribing] = useState(false);

  // Detect unsubscribe URL from email body (List-Unsubscribe heuristic)
  const unsubscribeUrl = (() => {
    const allBodies = emailsInThread.map((e) => e.body).join(" ");
    // Match common unsubscribe link patterns
    const regex1 = /href=["'](https?:\/\/[^"']*unsubscrib[^"']*)["']/i;
    const urlMatch = regex1.exec(allBodies);
    if (urlMatch?.[1]) return urlMatch[1];
    // Fallback: look for plain URLs with unsubscribe
    const regex2 = /(https?:\/\/\S*unsubscrib\S*)/i;
    const plainMatch = regex2.exec(allBodies);
    return plainMatch?.[1] ?? null;
  })();

  // tRPC mutations for AI
  const draftMutation = api.gmail.generateDraft.useMutation();
  const extractMutation = api.gmail.extractMeeting.useMutation();

  if (isLoading) {
    return (
      <div className="flex-1 flex items-center justify-center bg-background h-full text-text-muted theme-transition">
        <Loader2 className="w-8 h-8 animate-spin text-primary" />
      </div>
    );
  }

  if (emailsInThread.length === 0) {
    return (
      <div className="flex-1 flex flex-col items-center justify-center bg-background h-full text-text-muted p-8 theme-transition">
        <User className="w-10 h-10 text-text-muted/65 mb-2" />
        <p className="text-sm font-medium">No conversation selected</p>
        <p className="text-xs text-text-secondary mt-1">
          Select an email thread from the inbox to read.
        </p>
      </div>
    );
  }

  const latestEmail = emailsInThread[emailsInThread.length - 1]!;
  const subject = latestEmail.subject;

  // Toggle expand/collapse
  const toggleExpand = (id: string) => {
    setExpandedIds((prev) => ({
      ...prev,
      [id]: !prev[id],
    }));
  };

  // Helper to check if a message is expanded
  const isExpanded = (id: string, index: number) => {
    if (expandedIds[id] !== undefined) return expandedIds[id];
    return index === emailsInThread.length - 1; // Default last message to expanded
  };

  // AI draft assistant
  const handleAIDraft = async () => {
    setIsDrafting(true);
    try {
      const promptContext = `This is a reply to the email conversation with subject: "${subject}". Context of last message: "${latestEmail.bodyPreview}". Please draft a professional reply.`;
      const res = await draftMutation.mutateAsync({
        to: latestEmail.fromEmail,
        subject: `Re: ${subject}`,
        context: promptContext,
        tone: "professional",
      });
      if (res.draft) {
        setReplyBody(res.draft);
      }
    } catch (err) {
      console.error("Failed to generate AI draft:", err);
    } finally {
      setIsDrafting(false);
    }
  };

  // AI meeting extractor
  const handleExtractMeeting = async () => {
    setIsExtracting(true);
    try {
      const fullText = emailsInThread.map((e) => e.body).join("\n\n");
      const meeting = await extractMutation.mutateAsync({
        emailBody: fullText,
      });

      if (onScheduleMeeting) {
        onScheduleMeeting({
          title: meeting.title,
          attendees: meeting.attendees,
          suggestedTime: meeting.suggestedTime,
          duration: meeting.duration,
          description: `Meeting scheduled from email thread: "${subject}"`,
        });
      }
    } catch (err) {
      console.error("Meeting extraction failed:", err);
    } finally {
      setIsExtracting(false);
    }
  };

  const handleSendReply = async () => {
    if (!replyBody.trim()) return;
    await onReply(replyBody);
    setReplyBody("");
  };

  return (
    <div className="flex-1 flex flex-col h-full bg-background text-text-primary theme-transition">
      {/* Thread Header Toolbar */}
      <div className="px-6 py-4 border-b border-border/80 flex items-center justify-between gap-4 flex-shrink-0 bg-background/40 backdrop-blur">
        <div className="min-w-0">
          <h1 className="text-base font-bold text-text-primary truncate">{subject}</h1>
          <div className="flex items-center gap-2 mt-1.5 flex-wrap">
            <PriorityBadge label={latestEmail.priorityLabel} score={latestEmail.priorityScore} />
            {latestEmail.isSensitive && <ShieldBadge types={latestEmail.sensitiveTypes} />}
          </div>
        </div>

        {/* Action Buttons */}
        <div className="flex items-center gap-2">
          {/* Unsubscribe button — only shown if detected */}
          {unsubscribeUrl && (
            <a
              href={unsubscribeUrl}
              target="_blank"
              rel="noopener noreferrer"
              title="One-click unsubscribe from this mailing list"
              className="px-3 py-1.5 bg-error/10 hover:bg-error/20 text-error border border-error/25 hover:border-error/45 rounded-xl text-xs font-semibold flex items-center gap-1.5 transition duration-200 theme-transition"
            >
              <MailX className="w-3.5 h-3.5" />
              Unsubscribe
            </a>
          )}

          {/* Schedule Meeting button */}
          <button
            onClick={handleExtractMeeting}
            disabled={isExtracting}
            className="px-3 py-1.5 bg-primary/10 hover:bg-primary/20 text-primary-light border border-primary/25 hover:border-primary/45 rounded-xl text-xs font-semibold flex items-center gap-1.5 transition duration-200 disabled:opacity-50 theme-transition"
          >
            {isExtracting ? (
              <Loader2 className="w-3.5 h-3.5 animate-spin" />
            ) : (
              <Calendar className="w-3.5 h-3.5" />
            )}
            Schedule Meeting
          </button>

          {/* Star Action */}
          <button
            onClick={() => onToggleStar(latestEmail.gmailId, !latestEmail.isStarred)}
            className={`p-2 rounded-xl border border-border bg-surface transition hover:bg-surface-hover theme-transition ${
              latestEmail.isStarred ? "text-amber-400 border-amber-500/10" : "text-text-secondary hover:text-text-primary"
            }`}
          >
            <Star className="w-4 h-4" fill={latestEmail.isStarred ? "currentColor" : "none"} />
          </button>

          {/* Archive Action */}
          <button
            onClick={() => onArchive(latestEmail.gmailId)}
            className="p-2 rounded-xl border border-border bg-surface text-text-secondary hover:text-text-primary transition hover:bg-surface-hover theme-transition"
            title="Archive email (E)"
          >
            <Archive className="w-4 h-4" />
          </button>
        </div>
      </div>

      {/* Messages list scroller */}
      <div className="flex-1 overflow-y-auto px-6 py-4 space-y-4 scrollbar-thin">
        {emailsInThread.map((email, index) => {
          const expanded = isExpanded(email.id, index);
          const date = new Date(email.receivedAt);

          return (
            <div
              key={email.id}
              className={`border border-border/80 rounded-2xl overflow-hidden transition-all duration-200 bg-surface/85
                ${expanded ? "ring-1 ring-border/80 shadow-md valora-glow" : "opacity-75 hover:opacity-100"}`}
            >
              {/* Message Header Bar */}
              <div
                onClick={() => toggleExpand(email.id)}
                className="px-5 py-3.5 flex items-center justify-between cursor-pointer hover:bg-surface-hover/30 transition-colors"
              >
                <div className="flex items-center gap-3">
                  <div className="w-8 h-8 rounded-lg bg-surface-hover border border-border flex items-center justify-center font-bold text-xs text-text-secondary">
                    {email.fromName?.slice(0, 1) ?? email.fromEmail.slice(0, 1).toUpperCase()}
                  </div>
                  <div>
                    <span className="text-sm font-semibold text-text-primary">
                      {email.fromName ?? email.fromEmail}
                    </span>
                    <span className="text-xs text-text-muted ml-1.5 font-mono">
                      &lt;{email.fromEmail}&gt;
                    </span>
                  </div>
                </div>

                <div className="flex items-center gap-3">
                  <span className="text-xs text-text-muted font-mono">
                    {format(date, "MMM d, yyyy h:mm a")}
                  </span>
                  {expanded ? (
                    <ChevronDown className="w-4 h-4 text-text-muted" />
                  ) : (
                    <ChevronRight className="w-4 h-4 text-text-muted" />
                  )}
                </div>
              </div>

              {/* Message Body Content */}
              {expanded && (
                <div className="px-5 py-4 border-t border-border/60 bg-background/15">
                  {/* Recipients details */}
                  <div className="text-[10px] text-text-muted space-y-1 mb-4 pb-3 border-b border-border/40 font-sans">
                    <p>
                      <span className="font-semibold text-text-secondary">To:</span>{" "}
                      {email.toEmails.join(", ")}
                    </p>
                    {email.ccEmails.length > 0 && (
                      <p>
                        <span className="font-semibold text-text-secondary">Cc:</span>{" "}
                        {email.ccEmails.join(", ")}
                      </p>
                    )}
                  </div>

                  {/* Body HTML/Text rendering */}
                  {email.isSensitive && email.sensitiveTypes.length > 0 ? (
                    <SensitiveEmailBody body={email.body} types={email.sensitiveTypes} />
                  ) : email.body.includes("</") ? (
                    <div
                      className="text-sm text-text-secondary leading-relaxed overflow-x-auto whitespace-pre-wrap select-text font-sans"
                      dangerouslySetInnerHTML={{ __html: email.body }}
                    />
                  ) : (
                    <div className="text-sm text-text-secondary leading-relaxed overflow-x-auto whitespace-pre-wrap select-text font-sans [&_a]:text-primary-light [&_a]:underline hover:[&_a]:text-primary">
                      <ReactMarkdown remarkPlugins={[remarkGfm]}>
                        {cleanEmailText(email.body)}
                      </ReactMarkdown>
                    </div>
                  )}
                </div>
              )}
            </div>
          );
        })}
      </div>

      {/* Inline Reply Box at Bottom */}
      <div className="p-4 border-t border-border bg-surface flex-shrink-0 theme-transition">
        <div className="relative border border-border rounded-2xl bg-background p-2 focus-within:ring-1 focus-within:ring-primary focus-within:border-primary/50 focus-within:valora-glow transition duration-300">
          <textarea
            value={replyBody}
            onChange={(e) => setReplyBody(e.target.value)}
            placeholder={`Reply to ${latestEmail.fromName ?? latestEmail.fromEmail}...`}
            className="w-full bg-transparent border-0 outline-none focus:ring-0 text-sm text-text-primary placeholder-text-muted p-3 h-24 resize-none"
          />

          <div className="flex justify-between items-center px-2 pt-2 border-t border-border/60 mt-1">
            <div className="flex items-center gap-1.5">
              {/* AI Draft helper button */}
              <button
                onClick={handleAIDraft}
                disabled={isDrafting}
                className="px-3 py-1.5 bg-primary/10 hover:bg-primary/20 border border-primary/20 hover:border-primary/45 text-primary-light text-xs font-semibold rounded-xl flex items-center gap-1.5 transition disabled:opacity-50 theme-transition"
              >
                {isDrafting ? (
                  <Loader2 className="w-3.5 h-3.5 animate-spin" />
                ) : (
                  <Sparkles className="w-3.5 h-3.5" />
                )}
                AI Reply Assist
              </button>
            </div>

            <button
              onClick={handleSendReply}
              disabled={isReplying || !replyBody.trim()}
              className="px-4 py-1.5 bg-text-primary hover:bg-text-primary/90 disabled:bg-surface-hover disabled:text-text-muted text-background text-xs font-bold rounded-xl flex items-center gap-1.5 transition active:scale-95 duration-200 theme-transition"
            >
              {isReplying ? (
                <Loader2 className="w-3.5 h-3.5 animate-spin text-text-muted" />
              ) : (
                <Send className="w-3.5 h-3.5" />
              )}
              Send Reply
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
